platform:ios, '9.0'

target 'WanAndorid' do
    use_frameworks!
    
    pod 'FSPagerView'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'HandyJSON', '~>4.0.0-beta.1'
    pod 'Kingfisher'
    pod 'SnapKit'
    pod 'JSQWebViewController'
    pod 'ACTagView', '~> 2.2.4'
end
